#
# Copyright (c) 2025 Huawei Technologies Co., Ltd. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# This file is a part of the vllm-ascend project.
#

ARG VLLM_ASCEND_BRANCH=""
FROM quay.io/ascend/vllm-ascend:nightly-${VLLM_ASCEND_BRANCH}-a5

ARG PIP_INDEX_URL="https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
ARG AIS_BENCH_TAG="v3.1-20260609-master"
ARG AIS_BENCH_URL="https://github.com/AISBench/benchmark.git"
ARG GITEE_USERNAME=""
ARG GITEE_TOKEN=""

# Define environments
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /workspace

RUN pip config set global.index-url ${PIP_INDEX_URL}

# Install requirements-dev.txt for tests
RUN export PIP_EXTRA_INDEX_URL="https://repo.huaweicloud.com/ascend/repos/pypi" && \
    cd /vllm-workspace/vllm-ascend && \
    python3 -m pip install -r requirements-dev.txt && \
    python3 -m pip cache purge

# Install benchmark tools
RUN CLONE_URL=$(echo "${AIS_BENCH_URL}" | sed "s|https://|https://${GITEE_USERNAME}:${GITEE_TOKEN}@|") && \
    git clone -b ${AIS_BENCH_TAG} --depth 1 "${CLONE_URL}" /vllm-workspace/vllm-ascend/benchmark && \
    cd /vllm-workspace/vllm-ascend/benchmark && \
    pip install -e . -r requirements/api.txt -r requirements/extra.txt && \
    python3 -m pip cache purge

CMD ["/bin/bash"]
