#
# Copyright (c) 2025 Huawei Technologies Co., Ltd. All Rights Reserved.
# Copyright 2023 The vLLM team.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# This file is a part of the vllm-ascend project.
# Adapted from vllm-project/vllm/docs/source/conf.py
#

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import json
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

# -- Project information -----------------------------------------------------

project = "vllm-ascend"
copyright = "2025, vllm-ascend team"
author = "the vllm-ascend team"

# The full version, including alpha/beta/rc tags
release = "0.23.0rc1"

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.

# Copy from https://github.com/vllm-project/vllm/blob/main/docs/source/conf.py
extensions = [
    "sphinx.ext.napoleon",
    "sphinx.ext.intersphinx",
    "sphinx.ext.mathjax",
    "sphinx_copybutton",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "myst_parser",
    "sphinxarg.ext",
    "sphinx_design",
    "tools.docs_i18n.sphinx_extension",
    "sphinx_togglebutton",
    "sphinx_substitution_extensions",
    "tools.docs_codegen.sphinx_extension",
]

myst_enable_extensions = ["colon_fence", "amsmath", "dollarmath", "substitution"]

# Change this when cut down release
_REPO_ROOT = Path(__file__).resolve().parents[2]
_VLLM_MAIN_VERIFIED_COMMIT_PATH = _REPO_ROOT / ".github" / "vllm-main-verified.commit"
_VLLM_RELEASE_TAG_PATH = _REPO_ROOT / ".github" / "vllm-release-tag.commit"
_VLLM_MAIN_VERIFIED_COMMIT = _VLLM_MAIN_VERIFIED_COMMIT_PATH.read_text(encoding="utf-8").strip()
_VLLM_RELEASE_TAG = _VLLM_RELEASE_TAG_PATH.read_text(encoding="utf-8").strip()

myst_substitutions = {
    # the branch of vllm, used in vllm clone
    # - main branch: 'main'
    # - vX.Y.Z branch: 'vX.Y.Z'
    "vllm_version": "v0.23.0",
    # the branch of vllm-ascend, used in vllm-ascend clone and image tag
    # - main branch: 'main'
    # - vX.Y.Z branch: latest vllm-ascend release tag
    "vllm_ascend_version": "v0.23.0rc1",
    # the newest release version of vllm-ascend and matched vLLM, used in pip install.
    # This value should be updated when cut down release.
    "pip_vllm_ascend_version": "0.23.0rc1",
    "pip_vllm_version": "0.23.0",
    # CANN image tag paired with the vllm_ascend_version above
    "cann_image_tag": "9.1.0-910b-ubuntu22.04-py3.12",
    # vLLM commit hash for main branch
    "main_vllm_commit": _VLLM_MAIN_VERIFIED_COMMIT,
    # vLLM tag for main branch
    "main_vllm_tag": _VLLM_RELEASE_TAG,
    # Python version for main branch
    "main_python_version": ">= 3.10, < 3.13",
    # CANN version for main branch
    "main_cann_version": "9.1.0",
    # PyTorch/torch_npu version for main branch
    "main_pytorch_torch_npu_version": "2.10.0 / 2.10.0.post4",
    # Triton Ascend version for main branch
    "main_triton_ascend_version": "3.2.2",
}

# For cross-file header anchors
myst_heading_anchors = 5

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
locale_dirs = ["locale/"]
gettext_compact = False
# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    ".venv",
    "README.md",
    "user_guide/release.template.md",
    # TODO(yikun): Remove this after zh supported
    "**/*.zh.md",
]

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_title = project
html_theme = "sphinx_book_theme"
html_logo = "logos/vllm-ascend-logo-text-light.png"
html_theme_options = {
    "path_to_docs": "docs/source",
    "repository_url": "https://github.com/vllm-project/vllm-ascend",
    "use_repository_button": True,
    "use_edit_page_button": True,
}
# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# html_static_path = ['_static']
# Copy llms.txt to site root so it is available as /llms.txt.
html_extra_path = ["llms.txt"]

# -- Options for linkcheck builder -------------------------------------------

# Check external links without validating remote anchors. Many third-party
# sites render anchors dynamically, which makes anchor checks flaky in CI.
linkcheck_anchors = False
linkcheck_retries = 3
linkcheck_timeout = 15
linkcheck_workers = 10

# Example service endpoints in docs are intentionally not reachable from CI.
linkcheck_ignore = [
    r"https?://localhost(:\d+)?($|/.*)",
    r"https?://127\.0\.0\.1(:\d+)?($|/.*)",
    r"https?://0\.0\.0\.0(:\d+)?($|/.*)",
    r"https?://192\.0\.0\.1(:\d+)?($|/.*)",
    r"https?://<[^>]+>.*",
    r"https://github\.com/vllm-project/vllm-ascend/issues/new/choose",
    r"https://github\.com/[^/?#]+/?$",
    r"https?://.*\$%7B.*%7D.*",
]

READTHEDOCS_VERSION_TYPE = os.environ.get("READTHEDOCS_VERSION_TYPE")
if READTHEDOCS_VERSION_TYPE == "tag":
    # remove the warning banner if the version is a tagged release
    header_file = os.path.join(os.path.dirname(__file__), "_templates/sections/header.html")
    # The file might be removed already if the build is triggered multiple times
    # (readthedocs build both HTML and PDF versions separately)
    if os.path.exists(header_file):
        os.remove(header_file)

if __name__ == "__main__":
    print(json.dumps(myst_substitutions))
